# Generated by Django 4.0.3 on 2022-03-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_dress_lenght_alter_dress_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesitem',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clothesitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
