# Generated by Django 4.0.3 on 2022-03-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='species',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
