# Generated by Django 4.0.3 on 2022-03-20 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('shoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoes.shoes')),
                ('isShoeslace', models.BooleanField(default=True)),
            ],
            bases=('shoes.shoes',),
        ),
        migrations.CreateModel(
            name='HighHeels',
            fields=[
                ('shoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoes.shoes')),
                ('height', models.IntegerField()),
            ],
            bases=('shoes.shoes',),
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('shoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoes.shoes')),
                ('clinch', models.BooleanField(default=True)),
                ('sole', models.CharField(max_length=255)),
            ],
            bases=('shoes.shoes',),
        ),
        migrations.CreateModel(
            name='ShoesItem',
            fields=[
                ('barCode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('img', models.ImageField(upload_to='shoes/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('shoes', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='shoes.shoes')),
            ],
        ),
    ]
